name: C++ Google Test Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 1: Configure
    # Instead of "mkdir build" and "cd build", we use "-B build"
    # This automatically creates the folder and runs cmake inside it.
    - name: Configure CMake
      run: cmake -B build

    # Step 2: Build (Make)
    # We tell cmake to build the project located in the "build" folder
    - name: Build
      run: cmake --build build

    # Step 3: Run Tests
    # We run the executable directly from the build folder
    - name: Run Tests
      run: ./build/run_tests
