name: C++ Coverage Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install LCOV
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov

    - name: Configure CMake
      run: cmake -B build -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage" -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ./build/run_tests

    - name: Generate LCOV Report
      run: |
        # 1. Capture the data (FIXED: Added --ignore-errors mismatch)
        lcov --capture --directory build --output-file coverage.info --ignore-errors mismatch
        
        # 2. Remove clutter (system files and Google Test library code)
        lcov --remove coverage.info '/usr/*' '*/_deps/*' --output-file coverage_filtered.info --ignore-errors mismatch
        
        # 3. Generate HTML
        genhtml coverage_filtered.info --output-directory coverage_report --ignore-errors mismatch

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage_report
