name: C++ Google Test Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # We use Ubuntu because it has g++ and CMake pre-installed
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out your code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure CMake
    # IMPORTANT: This step reads your CMakeLists.txt and 
    # automatically downloads Google Test from the internet.
    - name: Configure CMake    
      run: chmod +x buildTesh.sh
    - name: Configure CMake    
      run: sudo ./buildTest.sh
